Traceback (most recent call last):
  File "/gpfsnyu/packages/anaconda3/5.2.0/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/gpfsnyu/packages/anaconda3/5.2.0/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/gpfsnyu/home/yy2564/few-shot-learning-cv/protoNet/experiments/proto_nets.py", line 25, in <module>
    assert torch.cuda.is_available()
AssertionError
